let companyNames = [
    "Mike Rowe soft",
    "Pear",
    "Outel",
    "Ice",
    "Tomsung",
    "Popsy",
    "Ohm Djezis",
    "Fizzer",
    "Wonder",
    "Global Hyper Mega Compunet",
    "Athena",
    "Hybrides",
    'Grimes Inc',
    'Wehner - Spencer',
    'Spinka Group',
    'Towne, Kilback and Mills',
    'Krajcik - Willms',
    'Wisoky - Jaskolski',
    'Pouros, DuBuque and Ledner',
    'Waelchi, Balistreri and Rath',
    'Ortiz, Dare and Schmitt',
    'Wilderman - Hackett',
    'Ortiz - Waelchi',
    'Nitzsche, Rowe and Murphy',
    'McGlynn - Leannon',
    'Lesch - Davis',
    'Russel, Hamill and Kozey',
    'Corkery - Grant',
    'Koepp, McGlynn and Glover',
    'Schmidt Group',
    'Prosacco - Lueilwitz',
    'McCullough - Kulas',
    'Fritsch and Sons',
    'Lemke and Sons',
    'Langworth, Kuhic and Schaden',
    'Borer and Sons',
    'Glover - Renner',
    'Zboncak, Lind and Stroman',
    'McKenzie, Williamson and Klocko',
    'Kub, Pfannerstill and Walker',
    'Herzog, Schmidt and Gaylord',
    'Gerlach, Harris and Hartmann',
    'Feest - Friesen',
    'Schaefer, Fahey and Wuckert',
    'Parker, Effertz and Moen',
    'Zulauf - Mueller',
    'Windler, Walker and Keebler',
    'Beatty, Rau and Renner',
    'Bernier - Marvin',
    'Auer and Sons',
    'Walter - Hagenes',
    'Harvey and Sons',
    "Tógan Labs", // with permission from Eilís Ní Fhlannagáin
];

module.exports = companyNames;
